version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Building lamda functions..."
      - cd lamda
      - zip -r ../lambda_functions.zip *
artifacts:
  files:
    - lambda_functions.zip
